### ISSUE TITLE
Add FreeCodeCamp favicon to the README.md

### ISSUE THREAD

**Issue by raisedadead** [VarCI/inspiring-github-templates#1]
The README.md does not have the logo of Free Code Camp. I went though the Contributing guide, and it states that updates will be overwritten.

Hence waiting for a response. Can make a pull request if confirmed.

/cc @BerkeleyTrue @QuincyLarson

**Comment by QuincyLarson** [comment]
@raisedadead Yes - I wasn't aware this was possible. Our favicons are here in various sizes if you'd like to create a PR: https://github.com/FreeCodeCamp/assets/blob/master/assets/logos/fcc_favicon_2016_07.zip

**Comment by jadb** [comment]
The favicons are automatically fetched from the projects' homepages if one exists. Manual changes to the README never persist. 

Let me think of a workaround for it.

**Comment by raisedadead** [comment]
@jadb Thanks for reverting! Looking forward to it. And awesome work with VarCI!

**Comment by raisedadead** [comment]
Sorry, Just cleaning up my issues queue. Thanks for your help & support.
